[project]
name = "inman"
version = "1.1.3"
description = "The basic inventory manager app."
dependencies = [
    "flask", "pdfkit", "pyvirtualdisplay"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
