[project]
name = "inman"
version = "1.0.2"
description = "The basic inventory manager app."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
