DROP TABLE IF EXISTS access;
DROP TABLE IF EXISTS asset_type;
DROP TABLE IF EXISTS company;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS inventory;

CREATE TABLE access (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE asset_type (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE company (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE location (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE status (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  access INTEGER NOT NULL,
  FOREIGN KEY (access) REFERENCES access (id)
);

CREATE TABLE inventory (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  asset_no TEXT UNIQUE NOT NULL,
  asset_type INTEGER NOT NULL,
  company INTEGER NOT NULL,
  location INTEGER NOT NULL,
  status INTEGER NOT NULL,
  normal_service TEXT NOT NULL DEFAULT 'None',
  due_service TEXT NOT NULL DEFAULT 'None',
  other_service TEXT NOT NULL DEFAULT 'None',
  remarks TEXT NOT NULL DEFAULT 'None',
  FOREIGN KEY (asset_type) REFERENCES asset_type (id),
  FOREIGN KEY (company) REFERENCES company (id),
  FOREIGN KEY (location) REFERENCES location (id),
  FOREIGN KEY (status) REFERENCES status (id)
);

INSERT INTO status VALUES (1, 'working');
INSERT INTO status VALUES (2, 'not-working');
INSERT INTO access VALUES (1, 'admin');
INSERT INTO access VALUES (2, 'regular');
